import localFont from "next/font/local";
import "./globals.css";

import { styled } from '@mui/material/styles';
// import BarExample from "./BarExample";
import DrawerLeft from "./DrawerLeft";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body> */}
      <body>

        <DrawerLeft children={children}></DrawerLeft>

        {/* <BarExample children={children} /> */}
      </body>
    </html>
  );
}































